S3_SR = 16000
S3_HOP = 160
S3_TOKEN_HOP = 640
S3_TOKEN_RATE = 25
SPEECH_VOCAB_SIZE = 6561

SOS = SPEECH_VOCAB_SIZE
EOS = SPEECH_VOCAB_SIZE + 1

SOT = "[START]"
EOT = "[STOP]"
UNK = "[UNK]"
SPACE = "[SPACE]"
SPECIAL_TOKENS = [SOT, EOT, UNK, SPACE, "[PAD]", "[SEP]", "[CLS]", "[MASK]"]
